### ISSUE TITLE
To get the server online-players' name

### ISSUE THREAD

**Issue by Because66666** [MCCTeam/MCCTeam.github.io#13]
Through a command or an api, we could get the server online-players' name. That is important for me to work with my bot.

**Comment by milutinke** [comment]
https://github.com/MCCTeam/Minecraft-Console-Client/blob/c2edd6f61925e72ca43ee642608a9f0a5314317c/MinecraftClient/Scripting/ChatBot.cs#L1252

**Comment by milutinke** [comment]
Don't use this repository for opening issues, ask on discord.
