### ISSUE TITLE
Autocommand 

### ISSUE THREAD

**Issue by Arshbir11** [MCCTeam/MCCTeam.github.io#14]
Hi i'm having issues with  the script scheduler 
when the server restarts or my acc get kicks for other reasons to hub It isn't sending the command to join the subserver in the server again i have to do it manually can you help ?

**Comment by Arshbir11** [comment]
it's like joining a realm from the main hub of the server  when the survival server restarts or my account got sent to hub for network issues or something i need a autocommand rule or something to send a command for joining the relm automatically

**Comment by milutinke** [comment]
Set `Trigger_On_Login` to `true` on the task that is supposed to switch you to the sub server.
I also recommend adding a delay, so the best solution is to create a txt script and then execute it via the `Action` field on the task.

**Comment by milutinke** [comment]
Just realized, this is an issue in a wrong repo.
Open it in the main one if you haven't solved it, or you can also make a thread on our Discord server.
