### ISSUE TITLE
[Idea] Use Vue Press

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/MCCTeam.github.io#2]
Hello, I'd like to contribute on this project too.
My suggestion is using [VuePress](https://vuepress.vuejs.org/), it's a static site generator for Markdown, it looks nice and is very simple to use.
Can I use it to setup the initial project?

My idea for pages:
- Introduction/About
- Installation (using pre-built and building from source)
- Configuration
- Usage
- Plugins Usage and Development
- Contributing

I would include already existing Youtube tutorials, and I'd record some of my own, basically making that every single page has a tutorial

**Comment by ORelio** [comment]
Hi! It would be nice indeed to have a simple, static page presenting the project. This repository was initially made to host the login redirection page, but having a home page would also be nice. The list of pages you suggest looks good. I'm not familiar with VuePress but feel free to use it if it's simple to use and maintain 🙂
