### ISSUE TITLE
Github not resolving the path

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/MCCTeam.github.io#4]
For some reason Github can't recognize the path: `https://mccteam.github.io/docs/.vuepress/dist/index.html`
I get 404.
Should we move the dist folder to the main one to test it out?

**Comment by ORelio** [comment]
Most likely, I'm not sure how this works. I'll give you access to this repository so you can try sorting this out.

**Comment by milutinke** [comment]
Okay, if it does not work out, we could host it on Netlify.
Mention me once you gave me the permissions.

**Comment by ORelio** [comment]
As long as the content is static, GitHub pages should work 🤔

**Comment by ORelio** [comment]
You need to accept the invite to the MCCTeam organization so that I can grant you access.

**Comment by milutinke** [comment]
Okay, I have the access, I'll try now

**Comment by milutinke** [comment]
Ok, got it working, I just need to reconfigure some stuff and make a script that will move the built files to the main folder/docs.

**Comment by milutinke** [comment]
Fixed. (Finally)
Everything works now.
You can change the README.md in the main repository to include the link.

I'll go through the documentation in the following days to check for mistakes, if there are any, it gets really hard to notice them when you're writing so much text.

**Comment by milutinke** [comment]
Also, a good idea would be to make an announcement in the Discussions section.

**Comment by ORelio** [comment]
The website looks great! 👏
Just updated the Readme and made an announcement on the main repository 🙂
