### ISSUE TITLE
Improve website main page (index.html)

### ISSUE THREAD

**Issue by ReinforceZwei** [MCCTeam/MCCTeam.github.io#7]
Currently `index.html` is a client-side redirect page only. It would shows a blank screen for a second before redirecting to document page. It would be better to avoid the redirection for user experience.

I would suggest either:
- Turn https://mccteam.github.io/docs/ into main page (remove the `/docs` subpath)
- Populate `index.html` with some content, maybe a page like https://mccteam.github.io/docs/ and add a button that link to the document page

**Comment by milutinke** [comment]
When I made it, I didn't want to mess up the existing files since they're used in the MCC for browser login, but yeah I guess I could change this behavior after the Phase 2 is done.

**Comment by ReinforceZwei** [comment]
Regarding redirect page for browser login, it should be fine as long as the `redirect.html` is untouched. If you are unsure, go to https://mccteam.github.io/redirect.html and check if the ~~ugly~~ page is still there. It would be great if you could also make a new charming redirect page, but I think that's for later.

**Comment by milutinke** [comment]
Fixed.
As for the Redirect page, I'll restyle it when I can.
